config/routes.rb
Lazyhub::Application.routes.draw do
  resources :subscriptions, :only => [:new, :create]

  resources :articles do
    member do 
       post :views
       get :views
       put "like", to: "articles#upvote"
       put "dislike", to: "articles#downvote"
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :comments, only: [:create, :destroy]
  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/game',    to: 'static_pages#game',    via: 'get'
  match '/laugh',    to: 'static_pages#laugh',    via: 'get'
  match '/news',    to: 'static_pages#news',    via: 'get'
  match '/tech',    to: 'static_pages#tech',    via: 'get'
  match '/social',    to: 'static_pages#social',    via: 'get'
  match '/sports',    to: 'static_pages#sports',    via: 'get'
  match '/random',    to: 'static_pages#random',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/articles/:id/like(.:format)',    to: 'articles#upvote',    via: 'get'
  match '/articles/:id/dislike(.:format)',    to: 'articles#downvote',    via: 'get'
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48206906-1', 'lazyhub.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_content.html.erb
<script>
    function fbShare(url, title, descr, image, winWidth, winHeight) 
    {
        var winTop = (screen.height / 2) - (winHeight / 2);
        var winLeft = (screen.width / 2) - (winWidth / 2);
        window.open('http://www.facebook.com/sharer.php?s=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url + '&p[images][0]=' + image, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight);
    }
</script>
<div id = "content">
<table class = "content_table">
<tbody>
    <% @articles.each do |article| %>
      <tr>
        <td class = "content_column">
            <ul id = "content_column">
              <li id = "title_div"><% if article.title.squish.length >= 50 %><%= article.title.squish[0...50] + "..."%><% else %><%= article.title %><% end %></li>
              <li><%= link_to fetch_image_tag(article.image_tag, :width => 500, :height => 250, :crop => :fill), views_article_path(article.id), target: :_blank, method: :post %></li>
              <div class = "statistics">
              <li id = "points_stats">Points: <%= (article.get_upvotes.size) %></li>
              <li id = "views_stats">Views: <%= article.views %></li>
              </div>
            </ul>
        </td>
        <td>
          <ul id = "content_actions">
            <% if signed_in? %>
            <li id = "upvote"><%= link_to like_article_path(article.id), remote: true do
              image_tag("upvote.jpg",  onmouseover: "this.src='#{asset_path('upvote_active.jpg')}'", onmouseout: "this.src='#{asset_path('upvote.jpg')}'", onclick: "this.src='#{asset_path('upvote_active.jpg')}'")
                end %></li>
            <li id = "downvote"><%= link_to dislike_article_path(article.id), remote: true do
              image_tag("downvote.jpg", onmouseover: "this.src='#{asset_path('downvote_active.jpg')}'", onmouseout: "this.src='#{asset_path('downvote.jpg')}'", onclick: "this.src='#{asset_path('downvote_active.jpg')}'")
              end %></li>
            <% else %>
            <li id = "upvote"><%= link_to like_article_path(article.id) do
              image_tag("upvote.jpg", onmouseover: "this.src='#{asset_path('upvote_active.jpg')}'", onmouseout: "this.src='#{asset_path('upvote.jpg')}'")
                end %></li>
            <li id = "downvote"><%= link_to dislike_article_path(article.id) do
              image_tag("downvote.jpg", onmouseover: "this.src='#{asset_path('downvote_active.jpg')}'", onmouseout: "this.src='#{asset_path('downvote.jpg')}'")
              end %></li>
            <% end %>
            <li><%= link_to image_tag("comment_button.jpg", :alt => "rss feed"), article %></li>
            <!--Social Media-->
            <li><%= link_to image_tag("facebook_share.jpg", :alt => "rss feed"), "javascript:fbShare('#{article.content}', 'Fb Share', 'Facebook share popup', '#{article.content}', 520, 350)" %></li>
            <li><%= link_to image_tag("twitter_share.jpg", :alt => "rss feed"), "https://twitter.com/intent/tweet?url=http%3A%2F%2Fwww.lazyhub.com/articles/#{article.id}/views&text=LazyHub&via=Lazy_Hub" %></li>
            <% if signed_in? %>
            <% if current_user.admin? && !current_user?(@user) %>
            <li><%= link_to 'Edit', edit_article_path(article) %></li>
            <li><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            <% end %>
            <% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- <%= link_to 'Post a Link to an Article', new_article_path, class: "btn btn-md btn-primary raised new_link_article_button" %> -->

<!-- <%= link_to 'Create a Text Post', new_article_path, class: "btn btn-md btn-primary raised new_text_article_button" %> -->

<!-- <%= render 'subscriptions/form' %> -->

<div id = "top5">
<table class = "top5_table">
  <thead>
    <tr>
      <td id = "top5_title">Most popular</td>
    </tr>
  </thead>
  
  <tbody>
    <% @count = 0 %>
    <% @top_articles.each do |article| %>
      <tr id = "top5_border">
        <td>
            <ul id = "content_column2">
              <% if @page == 'home' %>
                <li id = "article_type"><%= article.article_type %></li> 
              <% else %>
                <% @count += 1 %>
                <li id = "rank"><%= @count %></li>
              <% end %>
              <li id = "top_article_images"><%= link_to fetch_image_tag(article.image_tag, :width => 300, :height => 150, :crop => :fill), views_article_path(article.id), target: :_blank, method: :post %></li>
            </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<div id = "pagination" class = "digg_pagination"><%= will_paginate @articles %></div> 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact Us", contacts_path %></li>
    </ul>
  </nav>
  <small>
    <p>If you are the original creator of material featured on this website and want it removed, please contact the webmaster.<br>Copyright &copy 2017 Lazy Hub </p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Lazy Hub", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About Us",    about_path %></li>
          <% if signed_in? %> 
            <li id="fat-menu" class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <b class="home_gravatar"><%= gravatar_for(current_user, size: 23) %>
              </b>
              <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
        <ul class="nav pull-left">
          <li><%= link_to "News", news_path %></li>
          <li><%= link_to "Sports", sports_path %></li>
          <li><%= link_to "Tech", tech_path %></li>
          <li><%= link_to "Laugh",    laugh_path %></li>
          <li><%= link_to "Social", social_path %></li>
          <li><%= link_to "Game",    game_path %></li>
          <li><%= link_to "Random", random_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <a href="https://twitter.com/Lazy_Hub" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @Lazy_Hub</a>
      <script src="//platform.twitter.com/widgets.js"></script>
      <iframe class = "fb-like" src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Flazyhubs&amp;width=300&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:21px;" allowTransparency="true"></iframe>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/analytics' %>
  </body>
</html>